apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp3-deploy
spec:
  replicas: 3 # 3 Pods should exist at all times.
  selector:  # Pods label should be defined in ReplicaSet label selector
    matchLabels:
      app: myapp3
  template:
    metadata:
      name: myapp3-pod
      labels:
        app: myapp3 # Atleast 1 Pod label should match with ReplicaSet Label Selector
    spec:
      containers:
      - name: myapp3-container
        image: stacksimplify/kubenginx:3.0.0
        ports:
          - containerPort: 80