apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp1-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp1
  template: # Pod Creation
    metadata: # Information about the respectful pod
      name: myapp1-pod
      labels:
        app: myapp1 # At least 1 Pod label should match with ReplicaSet Label Selector
    spec: # Information about the container - Single Container Pod Preferable 
      containers:
      - name: myapp1-container
        image: stacksimplify/kubenginx:1.0.0
        ports:
          - containerPort: 80