kind: Service
apiVersion: v1
metadata:
  name:  myapp1-lb-service-nlb
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb    # To create Network Load Balancer  
spec:
  selector: # Important so the service know what pod (myapp1) to send the traffic
    app:  myapp1
  type:  LoadBalancer
  ports:
  - name:  http
    port:  80 # Service Port
    targetPort:  80 # Container Port