apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
spec:
  containers:
  - name: myapp-container
    image: myapp:latest
    ports:
    - containerPort: 80

# Types of Kubernetes Objects
# Pod, ReplicaSet, Deployment, Service and many more

# apiVersion: version of k8s objects
# kind: k8s objects 
# metadata: define name and labels for k8s objects
# spec: specification or real definition for k8s objects
